steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']

 # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/villager-rng:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/villager-rng:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'villager-rng'
  - '--image'
  - 'gcr.io/$PROJECT_ID/villager-rng:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'

images:
- 'gcr.io/$PROJECT_ID/villager-rng:$COMMIT_SHA'